### PR TITLE
fix: repo dev dependencies of cli components

### PR DESCRIPTION
**Pull request by AaronZyLee**
#### Description of changes

The recent release of CLI has major version bump for its component packages, which codegen repo has a dev dependency. Bump the dependency to next major version so that the `amplify-dev` will not break

Related packages:

- `amplify-cli-core`: `1.x` to `2.x`
- `graphql-transformer-core`: `6.x` to `7.x`

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] Breaking changes to existing customers are released behind a feature flag or major version update
- [ ] Changes are tested using sample applications for all relevant platforms (iOS/android/flutter/Javascript) that use the feature added/modified

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by alharris-at — APPROVED** [review]

**Review by phani-srikar — CHANGES_REQUESTED** [review]
We might want to upgrade these CLI package dependencies listed as `peerDependencies` in other places like inside `amplify-codegen, amplify-codegen-e2e-core and amplify-codegen-e2e-tests` too.

**Comment by alharris-at** [comment]
> so that the `amplify-dev` will not break

Did this package not break based on these as well? If not they may not be proper dev deps.

**Comment by AaronZyLee** [comment]
> > so that the `amplify-dev` will not break
> 
> Did this package not break based on these as well? If not they may not be proper dev deps.

Only dev deps but not for production

**Review by phani-srikar — APPROVED** [review]
LGTM!

**Pull request merged**
