### PR TITLE
feat: add angular codegen v6 support

### LINKED ISSUE #783: Angular code generation for v6 amplify
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.12.1

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen types

### Describe the bug

I'm following the tutorials in here [amplify](https://docs.amplify.aws/angular/build-a-backend/graphqlapi/mutate-data/). I'm trying to generate api.service.ts using `amplify codegen types`. But this package is creating older version of amplify what I mean is that it is trying to import 
```ts
import API, { graphqlOperation, GraphQLResult } from "@aws-amplify/api-graphql";
import { Observable } from "zen-observable-ts";
```
but it should do something like this: 

```ts
import { generateClient } from 'aws-amplify/api';
import * as mutations from './graphql/mutations';

const client = generateClient();

const updatedTodo = await client.graphql({
  query: mutations.updateTodo,
  variables: { input: {} }
});
```

### Expected behavior

it should create the new way of sending requests in the service.

### Reproduction steps

run `amplify codegen types`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AaronZyLee**
#### Description of changes

Added angular codegen support for JS V6

The new users will have the `amplifyJsLibraryVersion` with default value as `6` in their `.graphqlconfig.yml` file when running `amplify codegen add` and selecting the `angular` target. 

The old v5 angular users are not impacted as the config file is not modified. To opt-in the new codegen, they can run `amplify codegen remove` and `amplify codegen add` with the same `angular` option as target.

The old v5 angular is still available by editing the `.graphqlconfig.yml` file to switch the `amplifyJsLibraryVersion` from `6` to `5`.

The other inputs in this field are invalid with warning message and will fall into the v6 codegen behavior.

Changes for angular codegen v6 include:
- New import for `aws-amplify/api` and `rxjs`
```TypeScript
import { Injectable } from "@angular/core";
import { Client, generateClient, GraphQLResult } from "aws-amplify/api";
import { Observable } from "rxjs";
```
- Queries, mutations and subscriptions use the `generateClient` to execute APIs
```TypeScript
export class APIService {
  public client: Client;
  constructor() {
    this.client = generateClient();
  }

  async GetTodo(id: string): Promise<GetTodoQuery> {
    //...
    const response = (await this.client.graphql({
      query: statement,
      variables: gqlAPIServiceArguments
    })) as any;
    return <GetTodoQuery>response.data.getTodo;
  }

  async CreateTodo(
    input: CreateTodoInput,
    condition?: ModelTodoConditionInput
  ): Promise<CreateTodoMutation> {
    //...
    const response = (await this.client.graphql({
      query: statement,
      variables: gqlAPIServiceArguments
    })) as any;
    return <CreateTodoMutation>response.data.createTodo;
  }

  OnCreateTodoListener(
    filter?: ModelSubscriptionTodoFilterInput
  ): Observable<GraphQLResult<Pick<__SubscriptionContainer, "onCreateTodo">>> {
    //...
    return this.client.graphql({
      query: statement,
      variables: gqlAPIServiceArguments
    }) as any;
  }
}
```
#### Codegen Paramaters Changed or Added

New target `angularv6` in typegen
#### Issue #, if available

Fix #783 

#### Description of how you validated changes
- Unit and E2E tests
- Test new codegen with an [angular sample app](https://github.com/AaronZyLee/AngularV6CodegenSampleApp/tree/main)

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] Breaking changes to existing customers are released behind a feature flag or major version update
- [ ] Changes are tested using sample applications for all relevant platforms (iOS/android/flutter/Javascript) that use the feature added/modified
- [ ] Changes are tested on windows. Some Node functions (such as `path`) behave differently on windows.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by phani-srikar — COMMENTED** [review]
We previously had tests for when this new config property is undefined and we added unit tests for V6, can you also add a test when it's set to v5?

**Review by phani-srikar — APPROVED** [review]

**Comment by ashrielbrian** [comment]
@AaronZyLee @phani-srikar hey thanks a lot for the work done here! is it possible to expedite this and tag the members within the `amplify-data-admins` group for review?

**Review by dpilch — APPROVED** [review]

**Comment by elaf2001** [comment]
Could you provide an estimate on when the team plans to review and potentially merge this code? It would be helpful for those of us interested in the feature to have an idea of the timeline.

**Review by iartemiev — APPROVED** [review]
Giving admin approval for `API.md` changes, did not review the rest of the PR

**Pull request merged**
